version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}

  nginx:
    image: nginx:latest
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
        - "9090:80"
volumes:
  php_socket:
