version: "3.4"

services:
  php:
    build:
      context: .
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - assets:/srv/app/public/build
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite

  nginx:
    image: nginx:latest
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - assets:/srv/app/public/build
    ports:
        - "9090:80"
volumes:
  php_socket:
  assets:
