apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: php-socket
  name: php-socket
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 100Mi
