apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: symfony-demo
  name: symfony-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    io.kompose.service: symfony-demo
